#!/bin/bash

if [ -z "$PYFILE" ]; then
    echo "Error: Environment variable \$PYFILE is not set."
    exit 1
fi

if [ ! -f "$PYFILE" ]; then
    echo "Error: Python file \"$PYFILE\" does not exist."
    exit 1
fi

# Run the Python script using the python interpreter
python "$PYFILE"

